FROM mcr.microsoft.com/devcontainers/java:0-17

RUN apt -y update && apt -y upgrade

# RUN apt -y install openjdk-17-jdk
# RUN apt -y install mvn
# RUN apt -y install nodejs
RUN apk add --update nodejs npm